# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Dennis Erny
tagline:             'Frontend Developer'
description:         'Sr. Frontend Engineer <a href="https://twitter.com/sysomos">@sysomos</a>, <a href="http://armchairanalysis.com">NFL Data Analyst</a> and passionate student of UX/UI Design.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            3

# About/contact
author:
  name:              'Dennis Erny'
  url:               https://twitter.com/denniserny
  email:             erny.dennis@gmail.com

github:
  repo:              https://github.com/derny

# Custom vars
version:             1.0.0
