# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dennis Erny
tagline:             'Senior UI/Frontend Engineer'
description:         'Senior UI/Frontend Engineer and passionate student of UX/UI Design.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            3

# About/contact
author:
  name:              'Dennis Erny'
  url:               https://www.linkedin.com/in/denniserny
  email:             denniserny9@gmail.com

github:
  repo:              https://github.com/derny

# Custom vars
version:             1.0.0
